**

!cosheaf/
!cosheaf/**
!coflat-editor/
!coflat-editor/**

cosheaf/.git
cosheaf/.DS_Store
cosheaf/node_modules
cosheaf/dist
cosheaf/dist-server
cosheaf/test-results
cosheaf/.playwright-*
cosheaf/.vite
cosheaf/data
cosheaf/.env*

coflat-editor/.git
coflat-editor/.DS_Store
coflat-editor/node_modules
coflat-editor/dist
coflat-editor/test-results
coflat-editor/.playwright-*
coflat-editor/.vite
coflat-editor/.env*
