**

!cosheaf/
!cosheaf/**
!coflat/
!coflat/**

cosheaf/.git
cosheaf/.DS_Store
cosheaf/node_modules
cosheaf/dist
cosheaf/dist-server
cosheaf/test-results
cosheaf/.playwright-*
cosheaf/.vite
cosheaf/data
cosheaf/.env*

coflat/.git
coflat/.DS_Store
coflat/node_modules
coflat/dist
coflat/test-results
coflat/.playwright-*
coflat/.vite
coflat/.env*
